"""create_damage_classification_tables

Revision ID: 98d4ea91446c
Revises: 9327ce6829fd
Create Date: 2025-12-25 00:06:14.485694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98d4ea91446c'
down_revision: Union[str, Sequence[str], None] = '9327ce6829fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('classification_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confusion_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_table('damage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('damage_area', sa.Float(), nullable=False),
    sa.Column('damage_depth', sa.Float(), nullable=False),
    sa.Column('damage_point_count', sa.Integer(), nullable=False),
    sa.Column('component_age', sa.Integer(), nullable=False),
    sa.Column('usage_frequency', sa.Integer(), nullable=False),
    sa.Column('corrosion_level', sa.Integer(), nullable=False),
    sa.Column('deformation', sa.Float(), nullable=False),
    sa.Column('damage_level', sa.Enum('ringan', 'sedang', 'berat', name='damagelevel'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_records_id'), 'damage_records', ['id'], unique=False)
    op.create_table('prediction_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('damage_area', sa.Float(), nullable=False),
    sa.Column('damage_depth', sa.Float(), nullable=False),
    sa.Column('damage_point_count', sa.Integer(), nullable=False),
    sa.Column('component_age', sa.Integer(), nullable=False),
    sa.Column('usage_frequency', sa.Integer(), nullable=False),
    sa.Column('corrosion_level', sa.Integer(), nullable=False),
    sa.Column('deformation', sa.Float(), nullable=False),
    sa.Column('predicted_level', sa.Enum('ringan', 'sedang', 'berat', name='damagelevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_histories_id'), 'prediction_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_histories_id'), table_name='prediction_histories')
    op.drop_table('prediction_histories')
    op.drop_index(op.f('ix_damage_records_id'), table_name='damage_records')
    op.drop_table('damage_records')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
