"""add timestamps to models

Revision ID: ccd876b1905f
Revises: 98d4ea91446c
Create Date: 2025-12-28 15:34:50.330766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd876b1905f'
down_revision: Union[str, Sequence[str], None] = '98d4ea91446c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('components', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('damage_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('damage_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('model_metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('model_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('prediction_histories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('prediction_histories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_histories', 'updated_at')
    op.drop_column('prediction_histories', 'created_at')
    op.drop_column('model_metrics', 'updated_at')
    op.drop_column('model_metrics', 'created_at')
    op.drop_column('damage_records', 'updated_at')
    op.drop_column('damage_records', 'created_at')
    op.drop_column('components', 'updated_at')
    op.drop_column('components', 'created_at')
    # ### end Alembic commands ###
